### ISSUE TITLE
Invalid Response status when attempting to run oobabot

### ISSUE THREAD

**Issue by Phixia** [jmoney7823956789378/oobabot#1]
Giving your fork of oobabot a try today and it seems to be attempting to talk to api/v1/stream which does not look like a valid endpoint when looking at localhost:5000/docs

I believe it should be using localhost:5000/v1/completions but I'm not sure where to configure that?

```
←[33;40m2024-02-22 21:10:18,052←[0m←[37;40m  INFO ←[0m←[37;40mStarting oobabot, core version 0.2.3←[0m
←[33;45m2024-02-22 21:10:18,054←[0m←[37;45m WARNING ←[0m←[33;45mPyNaCl is not installed, voice will NOT be supported←[0m
←[33;40m2024-02-22 21:10:18,054←[0m←[37;40m  INFO ←[0m←[37;40mOobabooga is at http://localhost:5000←[0m
←[33;40m2024-02-22 21:10:20,092←[0m←[37;40m WARNING ←[0m←[33;40mCould not connect to Oobabooga server: [http://localhost:5000]←[0m
←[33;40m2024-02-22 21:10:20,092←[0m←[37;40m WARNING ←[0m←[33;40mPlease check the URL and try again.←[0m
←[33;40m2024-02-22 21:10:20,094←[0m←[37;40m ERROR ←[0m←[31;40mReason: 403, message='Invalid response status', url=URL('http://localhost:5000/api/v1/stream')←[0m
```

**Comment by jmoney7823956789378** [comment]
You're right, it is located here:
https://github.com/jmoney7823956789378/oobabot/blob/ff6bbe5e29d98d4a90345452466f0b4680ee7cf7/src/oobabot/settings.py#L584
When you use `--generate-config` it should populate new options:
```
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# oobabooga
# .
oobabooga:

  # Use the OpenAI API instead of the Oobabooga API.
  #   default: True
  use_openai:

  # OpenAI API key. Required if use_openai is True.
  #   default: awesome_api_key
  api_key:

  # OpenAI API completions endpoint. Defaults to the official OpenAI API URL.
  #   default: http://localhost:5000/v1/completions
  openai_endpoint:

  # Base URL for the oobabooga instance.  This should be ws://hostname[:port] for plain
  # websocket connections, or wss://hostname[:port] for websocket connections over TLS.
  #   default: ws://localhost:5005
  base_url:

  # Base URL for the oobabooga instance.  This should be ws://hostname[:port] for plain
  # websocket connections, or wss://hostname[:port] for websocket connections over TLS.
  #   default: http://localhost:5000
  base_blocking:
```

If you leave `use_openai: True`, then you should make sure to populate `openai_endpoint` with your api server's `completions` url.
