### ISSUE TITLE
Reason: Cannot connect to host localhost:5005

### ISSUE THREAD

**Issue by whyttt6** [jmoney7823956789378/oobabot#8]
2024-03-31 18:05:39,377  INFO Starting oobabot, core version 0.2.3
2024-03-31 18:05:39,379  INFO Oobabooga is at ws://localhost:5005
2024-03-31 18:05:43,432 WARNING Could not connect to Oobabooga server: [ws://localhost:5005]
2024-03-31 18:05:43,432 WARNING Please check the URL and try again.
2024-03-31 18:05:43,432 ERROR Reason: Cannot connect to host localhost:5005 ssl:default [Удаленный компьютер отклонил это сетевое подключение]

How to fix this?

**Comment by jmoney7823956789378** [comment]
@whyttt6 This could be anything.
Try taking a look and making sure you configured both oobabot and oobabooga's API correctly.

**Comment by xBelladonna** [comment]
I haven't tried to reproduce this issue, but it strikes me as something familiar. It looks like you're trying to use the old Oobabooga API that no longer exists (ws://localhost:5005). You should change your configuration file like this:
```yaml
oobabooga:
  # Base URL for the oobabooga instance.  This should be ws://hostname[:port] for plain
  # websocket connections, or wss://hostname[:port] for websocket connections over TLS.
  #   default: ws://localhost:5005
  # Legacy API
  # base_url: ws://legacy-api:5005
  # Use the OpenAI-compatible API
  use_openai: true
  openai_endpoint: http://localhost:5000/v1/completions
```
